### ISSUE TITLE
hetzner - Sponsor needed for T-Shirts 👚 👕 👚 👕 👚 👕 - 💰💰💰💰💰💰💰💰💰💰

### ISSUE THREAD

**Issue by meldron** [jscraftcamp/website#1302]
# Why T-Shirts?
We want to be a nice community of crafters and to show this we want to wear the same t-shirt.
This is also a nice souvenir, which reminds us about that great event.
Everybody who attends has the chance to give us his t-shirt size to register for a shirt.

# How does it work?
Last year we found a t-shirt shop in Munich which created nice prints on t-shirts made of high quality cotton.

# Additional info

In 2022 there was no time to order shirts and there was no sponsor

**Comment by lowsky** [comment]
Hi @wachri , thanks for your offer to sponsor this item.

(I move the communication from the [barbeque item](#1362#issuecomment-1539681500) to here, so that it is less confusing)

Would it possible to your marketing colleagues to send an email to team@jscraftcamp.org ? 
This will enable us to get the communication going, even when I will not be available or on vacation 🌴 

Thanks, and I looking forward to see you at JSCC23.

cc @meldron
