### ISSUE TITLE
Evaluate tooling for an online JSCC

### ISSUE THREAD

**Issue by s1hofmann** [jscraftcamp/website#929]
It doesn't look like the pandemic is going to disappear anytime soon, so we should evaluate ways to run #jscc21 online.

Since offerings for online conferencing evolved quite a bit in 2020 we should compare various tools.

Features for comparison could be e.g.

- Pricing
- Capacity
- Things like spatial areas, breakout rooms, agendas etc.
- Possibilities to integrate sponsors

Feel free to modify / extend this list and comment your results!

**Comment by wolframkriesing** [comment]
I think with something like https://workadventu.re/ where we can create a virtual world with rooms we can go to the next level  of open space, we can gather for a market place, book rooms, create schedules and the (imho) most important people can move around freely in the rooms, join rooms, sessions start and end whenever, no tight schedule, basically open space in the virtual space. I can even imagine mixing that once we eventually can be in some location in person.

**Comment by Narigo** [comment]
Something about sponsors in general: I attended a remote Hackathon last year where they sent out goodie bags to the registered people prior to the event. This could be done with t-shirts and similar sponsored items. This would also mean someone has to do the logistics for that and the collection of additional private data (= shipping addresses).

Anyways, I can't really say anything about hopin.com which has been used at the Hackathon as I was only a participant and the chat experience was pretty bad (video was okay though). I do have a bit of experience with wonder.me though, so here is my introduction to it:

# Wonder.me
[Wonder.me](https://www.wonder.me/) is another candidate which worked well for a smaller event we had recently. The event was more like a regular meetup though, with three talks and some more or less private discussions afterwards.

## Pricing
Wonder is free for now, probably until the end of 2021 according to their [FAQs](https://support.wonder.me/hc/en-us/articles/360013620818-What-is-the-price-cost-of-Wonder-).

## Capacity
It can host up to 1.500 people in the whole event but only 15 people per Circle. A Circle is the part where sessions would happen.

## Features and limitations
You can set one background image and create multiple areas which could basically indicate the rooms. There is a broadcasting feature to give a presentation or moderate the whole event. With the host password, you can broadcast your video to everybody (multiple people can join that broadcast to have some kind of panel, but they all share the host password).

I don't think it's currently possible to invite someone into the broadcast without sharing the host password but it's a highly requested feature according to their [feature request page](https://wonderme.canny.io/feature-requests).

You could let people gather in a line for market place, but since the broadcast feature is only available if you share the host password (and this allows various other things like changing the background image as well), it's probably better to write down the ideas and let moderators arrange the schedule.

## Sponsor integration
Sponsors could be integrated into the background image plus have the host password to have a short intro during broadcast and moderation.

**Comment by Narigo** [comment]
Did anybody try out https://hubs.mozilla.com/ yet?

**Comment by cowglow** [comment]
@marcthiele has use [https://vi.to/](Vito), for his online event [Stay Curious](staycurious.io)
